import { DataScope } from '@prisma/client'

export type BuiltInPermissionDefinition = {
  code: string
  name: string
  description?: string
}

export type BuiltInRoleDefinition = {
  name: string
  code: string
  description: string
  customerScope: DataScope
  reportScope: DataScope
  userManageScope: DataScope
  permissionCodes: string[]
}

export const BUILT_IN_ROLE_CODES = [
  'SUPER_ADMIN',
] as const satisfies readonly string[]

export const BUILT_IN_PERMISSION_DEFINITIONS: BuiltInPermissionDefinition[] = [
  { code: 'dashboard.view', name: '查看工作台' },
  { code: 'customers.view', name: '查看客户管理（含客户详情与业绩录单只读资料）' },
  { code: 'customers.create', name: '新增客户档案' },
  { code: 'customers.edit', name: '编辑客户档案' },
  { code: 'customers.follow', name: '跟进客户' },
  { code: 'customers.status', name: '变更客户状态' },
  { code: 'customers.delete', name: '删除客户档案' },
  { code: 'customers.phone.unmask', name: '查看手机号明文', description: '允许查看客户手机号明文，不再脱敏显示' },
  { code: 'customers.phone.unmask.self', name: '仅查看本人客户手机号明文', description: '允许查看本人名下客户手机号明文，非本人客户继续脱敏显示' },
  { code: 'contracts.view', name: '查看合同档案（含窗口内客户、人员、关联销售选项）' },
  { code: 'contracts.create', name: '新增合同档案' },
  { code: 'firstSales.view', name: '查看一销业绩' },
  { code: 'firstSales.create', name: '录入一销业绩' },
  { code: 'firstSales.edit', name: '编辑一销业绩' },
  { code: 'firstSales.time.edit', name: '修改一销录单时间', description: '允许修改一销业绩的业务录入时间' },
  { code: 'firstSales.delete', name: '删除一销业绩' },
  { code: 'firstSales.tail', name: '补录一销尾款' },
  { code: 'firstSales.review', name: '审核一销业绩' },
  { code: 'firstSales.review.single', name: '一销财务审核', description: '允许对单笔一销订单执行财务审核' },
  { code: 'firstSales.review.batch', name: '一销批量财务审核', description: '允许批量审核一销订单' },
  { code: 'firstSales.export', name: '一销导出', description: '允许导出一销业绩数据' },
  { code: 'secondSales.view', name: '查看二销管理（含录单窗口内客户资料与人员选项）' },
  { code: 'secondSales.assignment.view', name: '查看二销接待列表', description: '允许查看二销接待与分配列表' },
  { code: 'secondSales.orders.view', name: '查看二销业绩列表', description: '允许查看二销业绩列表与详情' },
  { code: 'secondSales.assign', name: '分配二销客户' },
  { code: 'secondSales.transfer', name: '转交二销客户到调解' },
  { code: 'secondSales.create', name: '录入二销业绩' },
  { code: 'secondSales.edit', name: '编辑二销业绩' },
  { code: 'secondSales.delete', name: '删除二销业绩' },
  { code: 'secondSales.time.edit', name: '修改二销录单时间', description: '允许修改二销业绩的业务录入时间' },
  { code: 'secondSales.review', name: '审核二销业绩' },
  { code: 'secondSales.review.single', name: '二销财务审核', description: '允许对单笔二销订单执行财务审核' },
  { code: 'secondSales.review.batch', name: '二销批量财务审核', description: '允许批量审核二销订单' },
  { code: 'secondSales.export', name: '二销导出', description: '允许导出二销业绩数据' },
  { code: 'thirdSales.view', name: '查看三销管理（含录单窗口内人员选项）' },
  { code: 'thirdSales.reception.view', name: '查看三销接待列表', description: '允许查看三销接待列表' },
  { code: 'thirdSales.orders.view', name: '查看三销业绩列表', description: '允许查看三销业绩列表与详情' },
  { code: 'thirdSales.create', name: '录入三销业绩' },
  { code: 'thirdSales.edit', name: '编辑三销业绩' },
  { code: 'thirdSales.delete', name: '删除三销业绩' },
  { code: 'thirdSales.time.edit', name: '修改三销录单时间', description: '允许修改三销业绩的业务录入时间' },
  { code: 'thirdSales.review', name: '审核三销业绩' },
  { code: 'thirdSales.review.single', name: '三销财务审核', description: '允许对单笔三销订单执行财务审核' },
  { code: 'thirdSales.review.batch', name: '三销批量财务审核', description: '允许批量审核三销订单' },
  { code: 'thirdSales.export', name: '三销导出', description: '允许导出三销业绩数据' },
  { code: 'reports.view', name: '查看业绩报表' },
  { code: 'reports.teamView', name: '查看团队业绩报表' },
  { code: 'reports.export', name: '导出业绩报表' },
  { code: 'reports.firstSales.view', name: '查看一销业绩报表（个人）', description: '允许查看一销个人业绩报表' },
  { code: 'reports.firstSales.teamView', name: '查看一销业绩报表（团队）', description: '允许查看一销团队业绩报表' },
  { code: 'reports.secondSales.view', name: '查看二销业绩报表（个人）', description: '允许查看二销个人业绩报表' },
  { code: 'reports.secondSales.teamView', name: '查看二销业绩报表（团队）', description: '允许查看二销团队业绩报表' },
  { code: 'reports.thirdSales.view', name: '查看三销业绩报表（个人）', description: '允许查看三销个人业绩报表' },
  { code: 'reports.thirdSales.teamView', name: '查看三销业绩报表（团队）', description: '允许查看三销团队业绩报表' },
  { code: 'legal.view', name: '查看法务系统（含窗口内用户选项）' },
  { code: 'legal.edit', name: '法务进度维护' },
  { code: 'legal.assign', name: '法务岗位分派' },
  { code: 'legal.filing.review', name: '立案审核' },
  { code: 'legal.pretrial.handle', name: '庭前办理' },
  { code: 'legal.close', name: '法务结案' },
  { code: 'legal.time.edit', name: '修改法务开始时间', description: '允许修改法务案件开始时间' },
  { code: 'legal.transfer', name: '法务转交三销' },
  { code: 'mediation.view', name: '查看调解系统' },
  { code: 'mediation.edit', name: '跟进/分配调解案件' },
  { code: 'mediation.complete', name: '完结调解案件' },
  { code: 'mediation.time.edit', name: '修改调解开始时间', description: '允许修改调解案件开始时间' },
  { code: 'oa.approvals.view', name: '查看OA审批' },
  { code: 'oa.approvals.create', name: '提交OA审批' },
  { code: 'oa.approvals.review', name: '审批OA申请' },
  { code: 'oa.approvals.pay', name: '执行OA付款' },
  { code: 'quality.view', name: '查看质检管理（含责任人选项）' },
  { code: 'quality.create', name: '新增质检记录' },
  { code: 'system.users.view', name: '查看用户' },
  { code: 'system.users.create', name: '新增用户' },
  { code: 'system.users.edit', name: '编辑用户' },
  { code: 'system.users.delete', name: '删除用户' },
  { code: 'system.users.status', name: '变更用户状态' },
  { code: 'system.roles.view', name: '查看角色权限' },
  { code: 'system.roles.create', name: '新增角色权限' },
  { code: 'system.roles.edit', name: '编辑角色权限' },
  { code: 'system.roles.delete', name: '删除角色权限' },
  { code: 'system.roles.assign', name: '分配角色人员' },
  { code: 'system.users.manage', name: '管理用户' },
  { code: 'system.departments.view', name: '查看部门' },
  { code: 'system.departments.create', name: '新增部门' },
  { code: 'system.departments.edit', name: '编辑部门' },
  { code: 'system.departments.delete', name: '删除部门' },
  { code: 'system.departments.manage', name: '管理部门' },
  { code: 'system.paymentAccounts.manage', name: '管理收款配置' },
  { code: 'system.courtConfig.view', name: '查看开庭配置' },
  { code: 'system.courtConfig.manage', name: '管理开庭配置' },
  { code: 'system.dingTalkReports.manage', name: '管理钉钉报单' },
  { code: 'system.roles.manage', name: '管理角色权限' },
  { code: 'judicialComplaint.view', name: '查看司法投诉', description: '允许查看司法投诉列表与详情' },
  { code: 'judicialComplaint.create', name: '新建司法投诉', description: '允许提交司法投诉表单' },
  { code: 'judicialComplaint.edit', name: '处理司法投诉', description: '允许修改司法投诉处理状态与进度' },
  { code: 'refund.view', name: '查看退款工单（含处理人和一销部门选项）', description: '允许查看退款工单列表、详情及窗口内基础选项' },
  { code: 'refund.create', name: '发起退款申请', description: '允许创建退款工单' },
  { code: 'refund.review', name: '审批退款工单', description: '允许审批通过或驳回退款工单' },
  { code: 'refund.assign', name: '分配退款处理人', description: '允许将退款工单分配给售后处理人' },
  { code: 'refund.edit', name: '跟进退款工单', description: '允许记录退款处理跟进' },
  { code: 'refund.close', name: '完结退款工单', description: '允许关闭退款工单' },
  { code: 'refund.department.edit', name: '修改退款一销归属', description: '允许修改退款单的一销团队与部门归属' },
  { code: 'refund.delete', name: '删除退款工单', description: '允许删除退款工单' },
]

const reportsPermissionCodes = [
  'reports.firstSales.view',
  'reports.firstSales.teamView',
  'reports.secondSales.view',
  'reports.secondSales.teamView',
  'reports.thirdSales.view',
  'reports.thirdSales.teamView',
]
const firstSalesPermissionCodes = [
  'customers.view',
  'customers.create',
  'customers.edit',
  'customers.follow',
  'customers.status',
  'customers.phone.unmask.self',
  'firstSales.view',
  'firstSales.create',
  'firstSales.edit',
  'firstSales.time.edit',
  'firstSales.delete',
  'firstSales.tail',
  'firstSales.review.single',
  'firstSales.export',
  'contracts.view',
  'contracts.create',
]
const secondSalesPermissionCodes = [
  'customers.view',
  'customers.edit',
  'customers.follow',
  'customers.status',
  'customers.phone.unmask.self',
  'secondSales.view',
  'secondSales.assignment.view',
  'secondSales.orders.view',
  'secondSales.assign',
  'secondSales.transfer',
  'secondSales.create',
  'secondSales.edit',
  'secondSales.delete',
  'secondSales.time.edit',
  'secondSales.review.single',
  'secondSales.export',
  'refund.create',
  'system.courtConfig.view',
]
const thirdSalesPermissionCodes = [
  'customers.view',
  'customers.phone.unmask.self',
  'thirdSales.view',
  'thirdSales.reception.view',
  'thirdSales.orders.view',
  'thirdSales.create',
  'thirdSales.edit',
  'thirdSales.delete',
  'thirdSales.time.edit',
  'thirdSales.export',
  'refund.create',
  'system.courtConfig.view',
]
const legalPermissionCodes = ['legal.view', 'legal.edit']
const legalManagerExtraPermissionCodes = ['legal.assign', 'legal.filing.review', 'legal.pretrial.handle', 'legal.close', 'legal.transfer']
const mediationPermissionCodes = ['mediation.view', 'mediation.edit', 'mediation.complete', 'mediation.time.edit', 'refund.create']
const qualityPermissionCodes = ['quality.view', 'quality.create']
const oaPermissionCodes = ['oa.approvals.view', 'oa.approvals.create', 'oa.approvals.review', 'oa.approvals.pay']
const contractPermissionCodes = ['contracts.view', 'contracts.create']
const refundManagerPermissionCodes = ['refund.view', 'refund.create', 'refund.review', 'refund.assign', 'refund.edit', 'refund.close', 'refund.department.edit', 'refund.delete', 'quality.view']
const refundPermissionCodes = ['refund.view', 'refund.create', 'refund.edit', 'refund.close', 'refund.delete', 'quality.view']
const managementPermissionCodes = [
  'dashboard.view',
  'system.users.view',
  'system.users.create',
  'system.users.edit',
  'system.users.delete',
  'system.users.status',
  'system.departments.view',
  'system.departments.create',
  'system.departments.edit',
  'system.departments.delete',
  'system.roles.view',
  'system.roles.create',
  'system.roles.edit',
  'system.roles.delete',
  'system.roles.assign',
  'system.users.manage',
  'system.departments.manage',
  'system.paymentAccounts.manage',
  'system.courtConfig.manage',
  'system.dingTalkReports.manage',
  'system.roles.manage',
  'customers.phone.unmask',
  'firstSales.review.single',
  'firstSales.review.batch',
  'secondSales.review.single',
  'secondSales.review.batch',
  'thirdSales.review.single',
  'thirdSales.review.batch',
  'firstSales.export',
  'secondSales.export',
  'thirdSales.export',
  'reports.firstSales.view',
  'reports.firstSales.teamView',
  'reports.secondSales.view',
  'reports.secondSales.teamView',
  'reports.thirdSales.view',
  'reports.thirdSales.teamView',
  'judicialComplaint.view',
  'judicialComplaint.create',
  'judicialComplaint.edit',
  'refund.view',
  'refund.create',
  'refund.review',
  'refund.assign',
  'refund.edit',
  'refund.close',
  'refund.department.edit',
  'refund.delete',
]

export const BUILT_IN_ROLE_DEFINITIONS: BuiltInRoleDefinition[] = [
  {
    name: '未分配角色',
    code: 'UNASSIGNED',
    description: '系统占位角色，未分配权限组的账号不可登录',
    customerScope: DataScope.SELF,
    reportScope: DataScope.SELF,
    userManageScope: DataScope.SELF,
    permissionCodes: [],
  },
  {
    name: '超管',
    code: 'SUPER_ADMIN',
    description: '系统最高权限',
    customerScope: DataScope.ALL,
    reportScope: DataScope.ALL,
    userManageScope: DataScope.ALL,
    permissionCodes: BUILT_IN_PERMISSION_DEFINITIONS.map((item) => item.code),
  },
  {
    name: '一销经理',
    code: 'FIRST_SALES_MANAGER',
    description: '负责一销团队管理及业绩审核',
    customerScope: DataScope.DEPARTMENT_AND_CHILDREN,
    reportScope: DataScope.DEPARTMENT_AND_CHILDREN,
    userManageScope: DataScope.DEPARTMENT_AND_CHILDREN,
    permissionCodes: Array.from(new Set(['dashboard.view', ...firstSalesPermissionCodes, ...reportsPermissionCodes, 'customers.phone.unmask', 'firstSales.review.batch'])),
  },
  {
    name: '一销主管',
    code: 'FIRST_SALES_SUPERVISOR',
    description: '负责一销团队带组',
    customerScope: DataScope.DEPARTMENT_AND_CHILDREN,
    reportScope: DataScope.DEPARTMENT_AND_CHILDREN,
    userManageScope: DataScope.DEPARTMENT,
    permissionCodes: Array.from(new Set(['dashboard.view', ...firstSalesPermissionCodes, 'customers.phone.unmask', 'reports.firstSales.teamView'])),
  },
  {
    name: '一销',
    code: 'FIRST_SALES',
    description: '一销业务人员',
    customerScope: DataScope.DEPARTMENT,
    reportScope: DataScope.DEPARTMENT,
    userManageScope: DataScope.SELF,
    permissionCodes: Array.from(new Set(['dashboard.view', ...firstSalesPermissionCodes, 'reports.firstSales.view'])),
  },
  {
    name: '二销经理',
    code: 'SECOND_SALES_MANAGER',
    description: '负责二销团队管理及复核',
    customerScope: DataScope.DEPARTMENT_AND_CHILDREN,
    reportScope: DataScope.DEPARTMENT_AND_CHILDREN,
    userManageScope: DataScope.DEPARTMENT_AND_CHILDREN,
    permissionCodes: Array.from(new Set(['dashboard.view', ...secondSalesPermissionCodes, ...reportsPermissionCodes, 'customers.phone.unmask', 'secondSales.review.batch'])),
  },
  {
    name: '二销主管',
    code: 'SECOND_SALES_SUPERVISOR',
    description: '负责二销组内分配与跟进',
    customerScope: DataScope.DEPARTMENT_AND_CHILDREN,
    reportScope: DataScope.DEPARTMENT_AND_CHILDREN,
    userManageScope: DataScope.DEPARTMENT,
    permissionCodes: Array.from(new Set(['dashboard.view', ...secondSalesPermissionCodes, 'customers.phone.unmask', 'reports.secondSales.teamView'])),
  },
  {
    name: '二销',
    code: 'SECOND_SALES',
    description: '二销业务人员',
    customerScope: DataScope.DEPARTMENT,
    reportScope: DataScope.DEPARTMENT,
    userManageScope: DataScope.SELF,
    permissionCodes: Array.from(new Set(['dashboard.view', ...secondSalesPermissionCodes, 'reports.secondSales.view'])),
  },
  {
    name: '人事主管',
    code: 'HR_MANAGER',
    description: '负责人事及权限组人员分配',
    customerScope: DataScope.SELF,
    reportScope: DataScope.SELF,
    userManageScope: DataScope.DEPARTMENT_AND_CHILDREN,
    permissionCodes: Array.from(new Set([
      'dashboard.view',
      'system.users.view',
      'system.users.create',
      'system.users.edit',
      'system.users.status',
      'system.departments.view',
      'system.roles.assign',
      'oa.approvals.view',
      'oa.approvals.create',
      'oa.approvals.review',
      ...legalPermissionCodes,
      ...mediationPermissionCodes,
      ...qualityPermissionCodes,
    ])),
  },
  {
    name: '人事',
    code: 'HR',
    description: '负责人事日常管理',
    customerScope: DataScope.SELF,
    reportScope: DataScope.SELF,
    userManageScope: DataScope.DEPARTMENT_AND_CHILDREN,
    permissionCodes: Array.from(new Set([
      'dashboard.view',
      'system.users.view',
      'system.users.create',
      'system.users.edit',
      'system.users.status',
      'system.departments.view',
      'oa.approvals.view',
      'oa.approvals.create',
      ...qualityPermissionCodes,
    ])),
  },
  {
    name: '三销',
    code: 'THIRD_SALES',
    description: '三销业务人员',
    customerScope: DataScope.DEPARTMENT,
    reportScope: DataScope.DEPARTMENT,
    userManageScope: DataScope.SELF,
    permissionCodes: Array.from(new Set(['dashboard.view', ...thirdSalesPermissionCodes, 'reports.thirdSales.view'])),
  },
  {
    name: '财务主管',
    code: 'FINANCE_MANAGER',
    description: '负责财务审核及报表导出',
    customerScope: DataScope.ALL,
    reportScope: DataScope.ALL,
    userManageScope: DataScope.SELF,
    permissionCodes: [
      'dashboard.view',
      'customers.phone.unmask',
      'firstSales.review.single',
      'firstSales.review.batch',
      'secondSales.review.single',
      'secondSales.review.batch',
      'thirdSales.review.single',
      'thirdSales.review.batch',
      'firstSales.export',
      'secondSales.export',
      'thirdSales.export',
      ...reportsPermissionCodes,
      ...oaPermissionCodes,
      ...contractPermissionCodes,
    ],
  },
  {
    name: '财务',
    code: 'FINANCE',
    description: '负责财务审核',
    customerScope: DataScope.ALL,
    reportScope: DataScope.ALL,
    userManageScope: DataScope.SELF,
    permissionCodes: [
      'dashboard.view',
      'firstSales.review.single',
      'secondSales.review.single',
      'thirdSales.review.single',
      'reports.firstSales.view',
      'reports.secondSales.view',
      'reports.thirdSales.view',
      ...oaPermissionCodes,
      ...contractPermissionCodes,
    ],
  },
  {
    name: '售后主管',
    code: 'AFTER_SALES_MANAGER',
    description: '负责售后及调解统筹',
    customerScope: DataScope.DEPARTMENT_AND_CHILDREN,
    reportScope: DataScope.DEPARTMENT_AND_CHILDREN,
    userManageScope: DataScope.DEPARTMENT,
    permissionCodes: Array.from(new Set(['dashboard.view', 'customers.phone.unmask', ...mediationPermissionCodes, ...qualityPermissionCodes, 'judicialComplaint.view', 'judicialComplaint.create', 'judicialComplaint.edit', ...refundManagerPermissionCodes])),
  },
  {
    name: '售后',
    code: 'AFTER_SALES',
    description: '负责售后跟进与调解处理',
    customerScope: DataScope.DEPARTMENT,
    reportScope: DataScope.DEPARTMENT,
    userManageScope: DataScope.SELF,
    permissionCodes: Array.from(new Set(['dashboard.view', ...mediationPermissionCodes, ...qualityPermissionCodes, 'judicialComplaint.view', 'judicialComplaint.create', ...refundPermissionCodes])),
  },
  {
    name: '后端管理',
    code: 'BACKEND_ADMIN',
    description: '负责后台配置维护',
    customerScope: DataScope.ALL,
    reportScope: DataScope.ALL,
    userManageScope: DataScope.SELF,
    permissionCodes: Array.from(new Set(['dashboard.view', ...managementPermissionCodes, ...reportsPermissionCodes])),
  },
  {
    name: '文员',
    code: 'CLERK',
    description: '负责基础录入及查询',
    customerScope: DataScope.DEPARTMENT,
    reportScope: DataScope.DEPARTMENT,
    userManageScope: DataScope.SELF,
    permissionCodes: ['dashboard.view', 'customers.view'],
  },
  {
    name: '合同专员',
    code: 'CONTRACT_SPECIALIST',
    description: '负责合同档案管理',
    customerScope: DataScope.DEPARTMENT,
    reportScope: DataScope.DEPARTMENT,
    userManageScope: DataScope.SELF,
    permissionCodes: Array.from(new Set(['dashboard.view', ...contractPermissionCodes])),
  },
  {
    name: '调解专员',
    code: 'MEDIATION_SPECIALIST',
    description: '负责调解案件处理',
    customerScope: DataScope.DEPARTMENT,
    reportScope: DataScope.DEPARTMENT,
    userManageScope: DataScope.SELF,
    permissionCodes: ['dashboard.view', 'customers.phone.unmask', 'mediation.view', 'mediation.edit', 'mediation.complete'],
  },
  {
    name: '法务主管',
    code: 'LEGAL_MANAGER',
    description: '负责法务团队管理及转交三销',
    customerScope: DataScope.DEPARTMENT_AND_CHILDREN,
    reportScope: DataScope.DEPARTMENT_AND_CHILDREN,
    userManageScope: DataScope.DEPARTMENT,
    permissionCodes: Array.from(new Set(['dashboard.view', 'customers.phone.unmask', ...legalPermissionCodes, ...legalManagerExtraPermissionCodes])),
  },
  {
    name: '法务',
    code: 'LEGAL',
    description: '负责法务案件办理',
    customerScope: DataScope.DEPARTMENT,
    reportScope: DataScope.DEPARTMENT,
    userManageScope: DataScope.SELF,
    permissionCodes: Array.from(new Set(['dashboard.view', 'customers.phone.unmask.self', ...legalPermissionCodes, 'legal.transfer'])),
  },
]

export const BUILT_IN_ROLE_PERMISSION_CODES_BY_ROLE = Object.fromEntries(
  BUILT_IN_ROLE_DEFINITIONS.map((role) => [role.code, role.permissionCodes]),
) as Record<string, string[]>
